# Cleaning riesgo natural

In [10]:
import geopandas as gpd

# Read the xlsx file into a pandas DataFrame
import pandas as pd
riesgo = gpd.read_file('../../../0_DATA/0_RAW/RIESGO_NATURAL/sintesis_riesgos.shp')  # Skip the first row, use the second row as column headers

In [11]:
riesgo

,OBJECTID,R_G1,R_H1,R_H2,R_H3,R_G2,SUMATORIA,geometry
0,1,None,None,None,None,Inestabilidad de laderas,1,"MULTIPOLYGON (((481202.577 2115603.035, 481202..."
1,2,None,None,None,Sequia,None,1,"MULTIPOLYGON (((493721.142 2106741, 493721.142..."
2,3,None,None,None,Sequia,Inestabilidad de laderas,2,"MULTIPOLYGON (((486401.142 2164805.49, 486401...."
3,4,None,None,None,Sequia,Inestabilidad de laderas,3,"MULTIPOLYGON (((500901.142 2119801, 500896.694..."
4,5,None,None,Olas de calor,None,None,1,"MULTIPOLYGON (((500841.142 2119421, 500841.142..."
5,6,None,None,Olas de calor,None,Inestabilidad de laderas,2,"MULTIPOLYGON (((485499.939 2162325.113, 485499..."
6,7,None,None,Olas de calor,None,Inestabilidad de laderas,3,"MULTIPOLYGON (((486979.716 2161142.902, 486980..."
7,8,None,None,Olas de calor,Sequia,None,2,"MULTIPOLYGON (((486108.391 2164661, 486101.142..."
8,9,None,None,Olas de calor,Sequia,None,3,"MULTIPOLYGON (((492436.716 2120782.698, 492438..."
9,10,None,None,Olas de calor,Sequia,Inestabilidad de laderas,4,"MULTIPOLYGON (((492338.572 2119921, 492321.142..."
10,11,None,None,Olas de calor,Sequia,Inestabilidad de laderas,5,"MULTIPOLYGON (((489201.142 2156681, 489181.142..."
11,12,None,Inundaciones,None,None,None,1,"MULTIPOLYGON (((480946.089 2111799.172, 480935..."
12,13,None,Inundaciones,None,None,Inestabilidad de laderas,2,"MULTIPOLYGON (((486390.508 2164885.945, 486390..."
13,14,None,Inundaciones,None,None,Inestabilidad de laderas,3,"MULTIPOLYGON (((484842.691 2121627.269, 484835..."
14,15,None,Inundaciones,None,Sequia,None,2,"MULTIPOLYGON (((486271.446 2164701, 486261.142..."
15,16,None,Inundaciones,None,Sequia,None,3,"MULTIPOLYGON (((499974.496 2119992.861, 499981..."
16,17,None,Inundaciones,None,Sequia,Inestabilidad de laderas,4,"MULTIPOLYGON (((484626.213 2121757.156, 484626..."
17,18,None,Inundaciones,None,Sequia,Inestabilidad de laderas,5,"MULTIPOLYGON (((498718.925 2127677.826, 498715..."
18,19,None,Inundaciones,Olas de calor,None,None,2,"MULTIPOLYGON (((486314.741 2164734.971, 486314..."
19,20,None,Inundaciones,Olas de calor,None,None,3,"MULTIPOLYGON (((484788.391 2122074.971, 484766..."
20,21,None,Inundaciones,Olas de calor,None,Inestabilidad de laderas,4,"MULTIPOLYGON (((487570.313 2122060.225, 487559..."
21,22,None,Inundaciones,Olas de calor,None,Inestabilidad de laderas,5,"MULTIPOLYGON (((469759.359 2142106.078, 469758..."
22,23,None,Inundaciones,Olas de calor,Sequia,None,4,"MULTIPOLYGON (((500558.987 2119873.798, 500548..."
23,24,None,Inundaciones,Olas de calor,Sequia,None,5,"MULTIPOLYGON (((484901.142 2122681, 484901.142..."
24,25,None,Inundaciones,Olas de calor,Sequia,Inestabilidad de laderas,5,"MULTIPOLYGON (((497528.601 2122681, 497528.296..."
25,26,Sismicidad,None,None,None,None,1,"MULTIPOLYGON (((503643.797 2126065.066, 503622..."
26,27,Sismicidad,None,None,None,Inestabilidad de laderas,2,"MULTIPOLYGON (((481848.779 2159391.838, 481808..."
27,28,Sismicidad,None,None,None,Inestabilidad de laderas,3,"MULTIPOLYGON (((490566.019 2134936.969, 490565..."
28,29,Sismicidad,None,None,Sequia,None,2,"MULTIPOLYGON (((484918.459 2159921, 484907.635..."
29,30,Sismicidad,None,None,Sequia,None,3,"MULTIPOLYGON (((503861.142 2126041, 503841.142..."
30,31,Sismicidad,None,None,Sequia,Inestabilidad de laderas,4,"MULTIPOLYGON (((493141.142 2133421, 493133.795..."
31,32,Sismicidad,None,None,Sequia,Inestabilidad de laderas,5,"MULTIPOLYGON (((493501.142 2138681, 493501.142..."
32,33,Sismicidad,None,Olas de calor,None,None,2,"MULTIPOLYGON (((492798.391 2155787.481, 492798..."
33,34,Sismicidad,None,Olas de calor,None,None,3,"MULTIPOLYGON (((493975.743 2132256.334, 493956..."
34,35,Sismicidad,None,Olas de calor,None,Inestabilidad de laderas,4,"MULTIPOLYGON (((492458.22 2134356.169, 492451...."
35,36,Sismicidad,None,Olas de calor,Sequia,None,4,"MULTIPOLYGON (((490621.142 2128281, 490611.827..."
36,37,Sismicidad,None,Olas de calor,Sequia,None,5,"MULTIPOLYGON (((498581.142 2133185.818, 498575..."
37,38,Sismicidad,Inundaciones,None,None,None,2,"MULTIPOLYGON (((484983.402 2160005.818, 484983..."
38,39,Sismicidad,Inundaciones,None,None,None,3,"MULTIPOLYGON (((500558.987 2127385.818, 500555..."
39,40,Sismicidad,Inundaciones,None,None,None,4,"MULTIPOLYGON (((489815.743 2128605.818, 489755..."
40,41,Sismicidad,Inundaciones,None,None,Inestabilidad de laderas,4,"MULTIPOLYGON (((488652.702 2131925.818, 488638..."
41,42,Sismicidad,Inundaciones,None,None,Inestabilidad de laderas,5,"MULTIPOLYGON (((495504.228 2133501.081, 495504..."
42,43,Sismicidad,Inundaciones,None,Sequia,None,4,"MULTIPOLYGON (((500569.811 2127385.818, 500561..."
43,44,Sismicidad,Inundaciones,None,Sequia,None,5,"MULTIPOLYGON (((492161.142 2127965.818, 492155..."
44,45,Sismicidad,Inundaciones,None,Sequia,Inestabilidad de laderas,5,"MULTIPOLYGON (((495461.142 2133301, 495444.572..."
45,46,Sismicidad,Inundaciones,Olas de calor,None,None,4,"MULTIPOLYGON (((500568.391 2127534.971, 500538..."
46,47,Sismicidad,Inundaciones,Olas de calor,None,None,5,"MULTIPOLYGON (((493956.411 2132267.158, 493956..."
47,48,Sismicidad,Inundaciones,Olas de calor,None,Inestabilidad de laderas,5,"MULTIPOLYGON (((495468.391 2133324.971, 495438..."
48,49,Sismicidad,Inundaciones,Olas de calor,Sequia,None,5,"MULTIPOLYGON (((491781.142 2128141, 491821.142..."
49,50,Sismicidad,Inundaciones,Olas de calor,Sequia,Inestabilidad de laderas,5,"MULTIPOLYGON (((492490.142 2136821, 492481.142..."
50,51,None,None,None,None,None,0,"MULTIPOLYGON (((493921.142 2107021, 493941.142..."

In [12]:
# Remove the OBJECTID column if it exists
if 'OBJECTID' in riesgo.columns:
    riesgo = riesgo.drop(columns=['OBJECTID'])

# Replace None with 0, else 1 for the specified columns
columns_to_clean = ['R_G1', 'R_H1', 'R_H2', 'R_H3', 'R_G2']
for col in columns_to_clean:
    if col in riesgo.columns:
        riesgo[col] = riesgo[col].apply(lambda x: 0 if x is None else 1)

# Rename columns to lowercase and update specific column names
riesgo = riesgo.rename(columns={
    'R_G1': 'sismicidad',
    'R_H1': 'inundacion',
    'R_H2': 'ola_calor',
    'R_H3': 'sequia',
    'R_G2': 'inestabilidad_ladera'
})

# Ensure all column names are lowercase
riesgo.columns = [col.lower() for col in riesgo.columns]

# Rename the 'geometry' column to 'geom'
if 'geometry' in riesgo.columns:
    riesgo = riesgo.rename(columns={'geometry': 'geom'})

# Display the updated GeoDataFrame
riesgo

,sismicidad,inundacion,ola_calor,sequia,inestabilidad_ladera,sumatoria,geom
0,0,0,0,0,1,1,"MULTIPOLYGON (((481202.577 2115603.035, 481202..."
1,0,0,0,1,0,1,"MULTIPOLYGON (((493721.142 2106741, 493721.142..."
2,0,0,0,1,1,2,"MULTIPOLYGON (((486401.142 2164805.49, 486401...."
3,0,0,0,1,1,3,"MULTIPOLYGON (((500901.142 2119801, 500896.694..."
4,0,0,1,0,0,1,"MULTIPOLYGON (((500841.142 2119421, 500841.142..."
5,0,0,1,0,1,2,"MULTIPOLYGON (((485499.939 2162325.113, 485499..."
6,0,0,1,0,1,3,"MULTIPOLYGON (((486979.716 2161142.902, 486980..."
7,0,0,1,1,0,2,"MULTIPOLYGON (((486108.391 2164661, 486101.142..."
8,0,0,1,1,0,3,"MULTIPOLYGON (((492436.716 2120782.698, 492438..."
9,0,0,1,1,1,4,"MULTIPOLYGON (((492338.572 2119921, 492321.142..."
10,0,0,1,1,1,5,"MULTIPOLYGON (((489201.142 2156681, 489181.142..."
11,0,1,0,0,0,1,"MULTIPOLYGON (((480946.089 2111799.172, 480935..."
12,0,1,0,0,1,2,"MULTIPOLYGON (((486390.508 2164885.945, 486390..."
13,0,1,0,0,1,3,"MULTIPOLYGON (((484842.691 2121627.269, 484835..."
14,0,1,0,1,0,2,"MULTIPOLYGON (((486271.446 2164701, 486261.142..."
15,0,1,0,1,0,3,"MULTIPOLYGON (((499974.496 2119992.861, 499981..."
16,0,1,0,1,1,4,"MULTIPOLYGON (((484626.213 2121757.156, 484626..."
17,0,1,0,1,1,5,"MULTIPOLYGON (((498718.925 2127677.826, 498715..."
18,0,1,1,0,0,2,"MULTIPOLYGON (((486314.741 2164734.971, 486314..."
19,0,1,1,0,0,3,"MULTIPOLYGON (((484788.391 2122074.971, 484766..."
20,0,1,1,0,1,4,"MULTIPOLYGON (((487570.313 2122060.225, 487559..."
21,0,1,1,0,1,5,"MULTIPOLYGON (((469759.359 2142106.078, 469758..."
22,0,1,1,1,0,4,"MULTIPOLYGON (((500558.987 2119873.798, 500548..."
23,0,1,1,1,0,5,"MULTIPOLYGON (((484901.142 2122681, 484901.142..."
24,0,1,1,1,1,5,"MULTIPOLYGON (((497528.601 2122681, 497528.296..."
25,1,0,0,0,0,1,"MULTIPOLYGON (((503643.797 2126065.066, 503622..."
26,1,0,0,0,1,2,"MULTIPOLYGON (((481848.779 2159391.838, 481808..."
27,1,0,0,0,1,3,"MULTIPOLYGON (((490566.019 2134936.969, 490565..."
28,1,0,0,1,0,2,"MULTIPOLYGON (((484918.459 2159921, 484907.635..."
29,1,0,0,1,0,3,"MULTIPOLYGON (((503861.142 2126041, 503841.142..."
30,1,0,0,1,1,4,"MULTIPOLYGON (((493141.142 2133421, 493133.795..."
31,1,0,0,1,1,5,"MULTIPOLYGON (((493501.142 2138681, 493501.142..."
32,1,0,1,0,0,2,"MULTIPOLYGON (((492798.391 2155787.481, 492798..."
33,1,0,1,0,0,3,"MULTIPOLYGON (((493975.743 2132256.334, 493956..."
34,1,0,1,0,1,4,"MULTIPOLYGON (((492458.22 2134356.169, 492451...."
35,1,0,1,1,0,4,"MULTIPOLYGON (((490621.142 2128281, 490611.827..."
36,1,0,1,1,0,5,"MULTIPOLYGON (((498581.142 2133185.818, 498575..."
37,1,1,0,0,0,2,"MULTIPOLYGON (((484983.402 2160005.818, 484983..."
38,1,1,0,0,0,3,"MULTIPOLYGON (((500558.987 2127385.818, 500555..."
39,1,1,0,0,0,4,"MULTIPOLYGON (((489815.743 2128605.818, 489755..."
40,1,1,0,0,1,4,"MULTIPOLYGON (((488652.702 2131925.818, 488638..."
41,1,1,0,0,1,5,"MULTIPOLYGON (((495504.228 2133501.081, 495504..."
42,1,1,0,1,0,4,"MULTIPOLYGON (((500569.811 2127385.818, 500561..."
43,1,1,0,1,0,5,"MULTIPOLYGON (((492161.142 2127965.818, 492155..."
44,1,1,0,1,1,5,"MULTIPOLYGON (((495461.142 2133301, 495444.572..."
45,1,1,1,0,0,4,"MULTIPOLYGON (((500568.391 2127534.971, 500538..."
46,1,1,1,0,0,5,"MULTIPOLYGON (((493956.411 2132267.158, 493956..."
47,1,1,1,0,1,5,"MULTIPOLYGON (((495468.391 2133324.971, 495438..."
48,1,1,1,1,0,5,"MULTIPOLYGON (((491781.142 2128141, 491821.142..."
49,1,1,1,1,1,5,"MULTIPOLYGON (((492490.142 2136821, 492481.142..."
50,0,0,0,0,0,0,"MULTIPOLYGON (((493921.142 2107021, 493941.142..."

In [13]:
import os

# Define the output directory
output_dir = '../../../0_DATA/1_CLEAN/RIESGO_NATURAL/'

# Create the directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# --- 1. Save the GeoDataFrame as a Shapefile (.shp) ---
# Note: Shapefiles truncate column names to 10 characters.
# 'tipo_impacto' will be saved as 'tipo_impa'.
points_filepath = os.path.join(output_dir, 'riesgo.parquet')
riesgo.to_parquet(points_filepath, index=False, engine='pyarrow')