# Process Crime data

## Get df and explore

In [7]:
import geopandas as gpd

# Read the xlsx file into a pandas DataFrame
import pandas as pd
AI_df = pd.read_excel('../../../0_DATA/0_RAW/CRIMEN/crimen/1_alto_impacto.xlsx', header=1)  # Skip the first row, use the second row as column headers
PG_df = pd.read_excel('../../../0_DATA/0_RAW/CRIMEN/crimen/2_perspectiva_genero.xlsx', header=1)
FE_df = pd.read_excel('../../../0_DATA/0_RAW/CRIMEN/crimen/3_fiscalia_esp.xlsx', sheet_name=None, header=1)

df_list = [AI_df, PG_df, FE_df]

In [4]:
AI_df

,ID,ID_CI,FECHA DE INICIO,HORA DE INICIO,CT - INICIO AP,TIPO IMPACTO,DELITO,MODALIDAD - DELITO,FECHA DE LOS HECHOS,HORA DE LOS HECHOS,CALLE 1 HECHOS,CALLE 2 HECHOS,COLONIA HECHOS,ALCALDÍA HECHOS,CT HECHOS,COORD X,COORD Y,OBSERVACIÓN
0,1,9881544,01/01/2025,03:16,IZP-9,ALTO IMPACTO,LESIONES DOLOSAS POR DISPARO DE ARMA DE FUEGO,LESIONES INTENCIONALES POR ARMA DE FUEGO,31/12/2024,13:21,HOSPITAL GENERAL DE IZTAPALAPA,SIN REGISTRO,SIN REGISTRO,IZTAPALAPA,FIIZP-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
1,2,9881555,01/01/2025,05:46,GAM-2,ALTO IMPACTO,LESIONES DOLOSAS POR DISPARO DE ARMA DE FUEGO,LESIONES INTENCIONALES POR ARMA DE FUEGO,01/01/2025,02:30,JOSE A CLAVE,PAGANINI,VALLEJO,GUSTAVO A MADERO,GAM-6,-99.13387924,19.46616991,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
2,3,9881564,01/01/2025,07:39,UAT-AO-4,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE MOTOCICLETA SIN VIOLENCIA,01/01/2025,02:00,PELICANO,SIN REGISTRO,GRANJAS MODERNAS,GUSTAVO A MADERO,GAM-7,-99.10292655,19.47661389,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
3,4,9881579,01/01/2025,10:37,FDS-7,ALTO IMPACTO,VIOLACIÓN,VIOLACION,06/09/2023,20:00,AVENUDA ARTEAGA Y SALAZAR,SIN REGISTRO,CONTADERO,CUAJIMALPA DE MORELOS,CJ-2,-99.30842727,19.33951859,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
4,5,9881629,01/01/2025,14:06,IZP-6,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE MOTOCICLETA SIN VIOLENCIA,01/01/2025,13:30,CERRADA JARRITO,SIN REGISTRO,LOMAS DE LA ESTANCIA,IZTAPALAPA,IZP-10,-99.00555083,19.33484067,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13442,13443,10041456,31/08/2025,22:30,UAT-TLP-3,ALTO IMPACTO,ROBO A TRANSEUNTE EN VÍA PÚBLICA CON Y SIN VIO...,ROBO A TRANSEUNTE EN VIA PUBLICA CON VIOLENCIA,31/08/2025,19:20,DZEMUL,PANABA,PEDREGAL DE SAN NICOLÁS 4A SECCIÓN,TLALPAN,TLP-1,-99.23155908,19.27712749,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13443,13444,10041457,31/08/2025,22:32,UAT-TLP-3,ALTO IMPACTO,ROBO A TRANSEUNTE EN VÍA PÚBLICA CON Y SIN VIO...,ROBO A TRANSEUNTE EN VIA PUBLICA CON VIOLENCIA,31/08/2025,06:00,HALACHO,CHUBURNA,PEDREGAL DE SAN NICOLÁS 3A SECCIÓN,TLALPAN,TLP-1,-99.23672891,19.28658234,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13444,13445,10041459,31/08/2025,22:35,UAT-GAM-8,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE MAQUINARIA SIN VIOLENCIA,31/07/2025,08:00,GRAN CANAL,SAN JUAN DE ARAGON,SAN PEDRO EL CHICO,GUSTAVO A MADERO,GAM-8,-99.09181327,19.47643131,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13445,13446,10041468,31/08/2025,23:33,UAT-AO-1,ALTO IMPACTO,ROBO A TRANSEUNTE EN VÍA PÚBLICA CON Y SIN VIO...,ROBO A TRANSEUNTE EN VIA PUBLICA CON VIOLENCIA,12/08/2025,05:30,ALTA TENSION,PROLONGACION SAN ANTONIO,SACRAMENTO,ALVARO OBREGON,AO-1,-99.19957727,19.38213339,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13446,13447,10041470,31/08/2025,23:50,CEN-B,ALTO IMPACTO,ROBO A TRANSEUNTE EN VÍA PÚBLICA CON Y SIN VIO...,ROBO A TRANSEUNTE EN VIA PUBLICA SIN VIOLENCIA,26/07/2025,01:00,AV JOSE LORETO FABELA,AV FRANCISCO MORAZAN,SAN JUAN DE ARAGÓN VII SECCIÓN,GUSTAVO A MADERO,GAM-5,-99.07777171,19.47849851,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...

In [40]:
AI_df[(AI_df['COORD X'] == 'SIN REGISTRO') | (AI_df['COORD Y'] == 'SIN REGISTRO')]

,ID,ID_CI,FECHA DE INICIO,HORA DE INICIO,CT - INICIO AP,TIPO IMPACTO,DELITO,MODALIDAD - DELITO,FECHA DE LOS HECHOS,HORA DE LOS HECHOS,CALLE 1 HECHOS,CALLE 2 HECHOS,COLONIA HECHOS,ALCALDÍA HECHOS,CT HECHOS,COORD X,COORD Y,OBSERVACIÓN
0,1,9881544,01/01/2025,03:16,IZP-9,ALTO IMPACTO,LESIONES DOLOSAS POR DISPARO DE ARMA DE FUEGO,LESIONES INTENCIONALES POR ARMA DE FUEGO,31/12/2024,13:21,HOSPITAL GENERAL DE IZTAPALAPA,SIN REGISTRO,SIN REGISTRO,IZTAPALAPA,FIIZP-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
34,35,9901007,01/02/2025,14:20,ORIENTEII,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE MOTOCICLETA SIN VIOLENCIA,21/01/2025,17:00,NO ESPECIFICA LUGAR DE HECHOS,SIN REGISTRO,SIN REGISTRO,SIN REGISTRO,CDMX-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
38,39,9901044,01/02/2025,15:11,CEN-A,ALTO IMPACTO,ROBO A PASAJERO A BORDO DEL METRO CON Y SIN VI...,ROBO A PASAJERO A BORDO DE METRO SIN VIOLENCIA,31/01/2025,06:30,NO INDICA LUGAR DE HECHOS,SIN REGISTRO,SIN REGISTRO,SIN REGISTRO,CDMX-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
54,55,9901154,01/02/2025,18:45,UAT-MH-4,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE MOTOCICLETA SIN VIOLENCIA,01/02/2025,12:00,NO INDICA LUGAR DE HECHOS,SIN REGISTRO,SIN REGISTRO,SIN REGISTRO,CDMX-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
64,65,9901250,01/02/2025,22:43,CEN-A,ALTO IMPACTO,ROBO A PASAJERO A BORDO DEL METRO CON Y SIN VI...,ROBO A PASAJERO A BORDO DE METRO SIN VIOLENCIA,31/01/2025,07:15,NO INDICA LUGAR EXACTO DE HECHOS,SIN REGISTRO,SIN REGISTRO,SIN REGISTRO,CDMX-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13324,13325,10040233,29/08/2025,14:51,ORIENTEII,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VI...,26/08/2025,00:00,CALLE,SIN REGISTRO,SIN REGISTRO,SIN REGISTRO,CDMX-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13346,13347,10040547,29/08/2025,22:19,ORIENTEII,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VI...,15/08/2025,20:30,NO SE ESPECIFICA EL LUGAR DE LOS HECHOS,SIN REGISTRO,SIN REGISTRO,SIN REGISTRO,CDMX-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13349,13350,10040580,29/08/2025,23:31,ORIENTEII,ALTO IMPACTO,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,ROBO DE MOTOCICLETA SIN VIOLENCIA,25/08/2025,22:30,SE IGNORA LUGAR DE HECHOS,- NO SCINCE -,SIN REGISTRO,SIN REGISTRO,CDMX-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13401,13402,10041066,31/08/2025,02:19,59,ALTO IMPACTO,VIOLACIÓN,VIOLACION EQUIPARADA,30/08/2025,20:30,DOCTORES,NO ESPECIFICA EL LUGA DE LOS HECHOS,SIN REGISTRO,CUAUHTEMOC,FICUH-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
13438,13439,10041442,31/08/2025,22:00,59,ALTO IMPACTO,VIOLACIÓN,VIOLACION EQUIPARADA,30/08/2025,12:00,AV INSURGENTES SUR,SE ENCONTRO LA CALL EN LA COLOIA,SIN REGISTRO,TLALPAN,FITLP-0,SIN REGISTRO,SIN REGISTRO,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...

In [5]:
PG_df

,ID,ID_CI,FECHA DE INICIO,HORA DE INICIO,CT - INICIO AP,TIPO IMPACTO,DELITO,MODALIDAD - DELITO,FECHA DE LOS HECHOS,HORA DE LOS HECHOS,CALLE 1 HECHOS,CALLE 2 HECHOS,COLONIA HECHOS,ALCALDÍA HECHOS,CT HECHOS,COORD. X,COORD. Y,OBSERVACION
0,1,9881574,01/01/2025,09:44,COY-4,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,01/01/2025,06:45,REY MOCTEZUMA,SIN REGISTRO,AJUSCO,COYOACAN,COY-4,-99.15758455,19.32890745,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
1,2,9881589,01/01/2025,11:42,59,BAJO IMPACTO,DELITO DE BAJO IMPACTO,ABUSO SEXUAL,01/01/2025,08:30,SUR 141,NO SE ESPECIFICA,AMPLIACIÓN GABRIEL RAMOS MILLÁN,IZTACALCO,IZC-2,-99.09850259,19.39042177,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
2,3,9881594,01/01/2025,12:01,CJM-IZP,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,28/12/2024,19:00,JAZMIN,SIN REGISTRO,LOMAS DE SAN LORENZO,IZTAPALAPA,IZP-8,-99.05916901,19.31661583,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
3,4,9881595,01/01/2025,12:09,75,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,01/01/2025,02:30,HILARIO ELGUERA,SIN REGISTRO,SAN MIGUEL,IZTACALCO,IZC-1,-99.1153277,19.39305887,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
4,5,9881599,01/01/2025,12:24,COY-4,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,24/12/2024,10:15,TECACALO,SIN REGISTRO,ADOLFO RUIZ CORTINES,COYOACAN,COY-4,-99.14638025,19.31853912,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23382,23383,10041466,31/08/2025,23:23,UAT-IZC-2,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,31/08/2025,21:00,SUR 157,ORIENTE 120,AMPLIACIÓN GABRIEL RAMOS MILLÁN,IZTACALCO,IZC-2,-99.09785361,19.38619038,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
23383,23384,10041471,31/08/2025,23:37,75,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,31/08/2025,20:30,TERCERA CERRADA DE JOYA DE NIEVES,SIN REGISTRO,ARBOLEDAS DE CUAUTEPEC EL ALTO,GUSTAVO A MADERO,GAM-1,-99.12633134,19.55824836,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
23384,23385,10041472,31/08/2025,23:39,CJM-AZ,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,31/08/2025,10:30,GENERAL ARISTA,SIN REGISTRO,ARGENTINA PONIENTE,MIGUEL HIDALGO,MH-1,-99.2096279,19.45960785,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
23385,23386,10041473,31/08/2025,23:47,CJM-TLP,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,30/08/2025,20:00,TERCERA CERRADA DE CINCO DE MAYO VIA PUBLICA,SIN REGISTRO,SAN FRANCISCO CULHUACAN,COYOACAN,COY-3,-99.11580288,19.33659371,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...
23386,23387,10041475,31/08/2025,23:59,UAT-MC-1,BAJO IMPACTO,DELITO DE BAJO IMPACTO,VIOLENCIA FAMILIAR,31/08/2025,23:00,MOCTEZUMA,PALMILLA,EL ROSAL,LA MAGDALENA CONTRERAS,MC-1,-99.25149619,19.30760966,* LAS COORDENADAS QUE SE MUESTRAN NO CORRESPON...

In [9]:
# Iterate through all sheets in the Excel file
sheet_dfs = {}
for sheet_name, sheet_df in FE_df.items():
    # Check if the column 'COORD. X' is in the DataFrame
    if 'COORD. X' in sheet_df.columns:
        # Store the DataFrame in a dictionary with the sheet name as the key
        sheet_dfs[sheet_name] = sheet_df
        print(f"Created DataFrame for sheet: {sheet_name}")
    else:
        print(f"Skipped sheet: {sheet_name} (does not contain 'COORD. X')")

Created DataFrame for sheet: FIEC
Created DataFrame for sheet: FIDCANNA
Created DataFrame for sheet: FDMDFDB
Created DataFrame for sheet: FIEAE
Created DataFrame for sheet: FIEDF
Created DataFrame for sheet: FIDS
Created DataFrame for sheet: FIEDH
Created DataFrame for sheet: FIDN
Created DataFrame for sheet: FIERVT
Created DataFrame for sheet: FIDDS
Created DataFrame for sheet: FIDMTP
Created DataFrame for sheet: FIDCSP
Created DataFrame for sheet: FIDAGAP
Created DataFrame for sheet: FIDAMPU
Created DataFrame for sheet: FIDVF

In [10]:
sheet_dfs['Carp_fisc'] = AI_df
sheet_dfs['Persp_gen'] = PG_df

In [11]:
sheet_dfs.keys()

dict_keys(['FIEC', 'FIDCANNA', 'FDMDFDB', 'FIEAE', 'FIEDF', 'FIDS', 'FIEDH', 'FIDN', 'FIERVT', 'FIDDS', 'FIDMTP', 'FIDCSP', 'FIDAGAP', 'FIDAMPU', 'FIDVF', 'Carp_fisc', 'Persp_gen'])

## Clean

In [17]:
import geopandas as gpd
import pandas as pd
import re
from unidecode import unidecode

def process_crime_data(df):
    """
    Cleans, processes, and converts crime data from a pandas DataFrame to a GeoDataFrame,
    keeping only records from 2025 onwards or those with no date.
    """
    # Standardize column names to handle variations
    df.columns = [
        re.sub(r'_+', '_', unidecode(col).lower().replace(' ', '_').replace('-', '_').strip())
        for col in df.columns
    ]

    # Rename columns to a standard format
    columns_mapping = {
        'id_ci': 'id_ci',
        'fecha_de_los_hechos': 'fecha_de_los_hechos',
        'hora_de_los_hechos': 'hora_de_los_hechos',
        'alcaldia_hechos': 'alcaldia_hechos',
        'colonia_hechos': 'colonia_hechos',
        'calle_1_hechos': 'calle_1_hechos',
        'calle_2_hechos': 'calle_2_hechos',
        'tipo_impacto': 'tipo_impacto',
        'delito': 'delito',
        'modalidad_delito': 'modalidad_delito',
        'coord._x': 'coord_x',
        'coord_x': 'coord_x',
        'coord._y': 'coord_y',
        'coord_y': 'coord_y'
    }
    df = df.rename(columns=columns_mapping)
    
    # Ensure all required columns are present
    required_columns = [
        'id_ci','fecha_de_los_hechos', 'hora_de_los_hechos', 'alcaldia_hechos', 'colonia_hechos',
        'calle_1_hechos', 'calle_2_hechos', 'tipo_impacto', 'delito', 'modalidad_delito',
        'coord_x', 'coord_y'
    ]
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        print(f"Warning: Missing columns {missing_columns}. Skipping this DataFrame.")
        return None

    df = df[required_columns]

    print(f"Initial DataFrame shape: {df.shape}")

    # Normalize string columns
    for col in df.select_dtypes(include='object').columns:
        if col not in ['coord_x', 'coord_y']:
            df[col] = df[col].apply(lambda x: re.sub(r'_+', '_', unidecode(x.lower())) if isinstance(x, str) else x)

    # Convert date and time columns
    df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')
    
    # Filter to only keep records from 2025 onwards or with a null date
    df = df[(df['fecha_de_los_hechos'] >= '2025-01-01') | (df['fecha_de_los_hechos'].isna())]
    
    df['hora_de_los_hechos'] = pd.to_datetime(df['hora_de_los_hechos'], format='%H:%M', errors='coerce').dt.time
    
    # Clean and convert coordinate columns to a numeric type
    df['coord_x'] = pd.to_numeric(df['coord_x'].replace('sin registro', pd.NA), errors='coerce')
    df['coord_y'] = pd.to_numeric(df['coord_y'].replace('sin registro', pd.NA), errors='coerce')

    # Drop rows with any missing coordinate values
    df.dropna(subset=['coord_x', 'coord_y'], inplace=True)
    print(f"Shape after dropping NaN coordinates: {df.shape}")

    if df.empty:
        print("Warning: DataFrame is empty after filtering. Returning an empty GeoDataFrame.")
        return gpd.GeoDataFrame()

    # Create the GeoDataFrame
    gdf = gpd.GeoDataFrame(
        df,
        geometry=gpd.points_from_xy(df.coord_x, df.coord_y),
        crs="EPSG:6372"  # Set the Coordinate Reference System to SRID 6372
    )
    # Drop original coordinate columns
    gdf = gdf.drop(columns=['coord_x', 'coord_y'])
    
    # Order the final GeoDataFrame by date
    gdf = gdf.sort_values(by='fecha_de_los_hechos').reset_index(drop=True)
    
    return gdf

In [41]:
gdf_list = []
for df in sheet_dfs.values():
    # Get the variable name of the DataFrame (e.g., AI_df, PG_df, FE_df)
    df_name = [name for name in globals() if globals()[name] is df][0]
    gdf_name = df_name.replace('_df', '_geo')
    gdf = process_crime_data(df)
    globals()[gdf_name] = gdf
    gdf_list.append(gdf)

Initial DataFrame shape: (438, 12)
Shape after dropping NaN coordinates: (325, 12)
Initial DataFrame shape: (5927, 12)

C:\Users\eduar\AppData\Local\Temp\ipykernel_10412\3669253117.py:57: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')
C:\Users\eduar\AppData\Local\Temp\ipykernel_10412\3669253117.py:57: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')

Shape after dropping NaN coordinates: (4180, 12)
Initial DataFrame shape: (31, 12)
Shape after dropping NaN coordinates: (20, 12)
Initial DataFrame shape: (172, 12)
Shape after dropping NaN coordinates: (52, 12)
Initial DataFrame shape: (1397, 12)
Shape after dropping NaN coordinates: (217, 12)

C:\Users\eduar\AppData\Local\Temp\ipykernel_10412\3669253117.py:57: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')

Initial DataFrame shape: (3429, 12)
Shape after dropping NaN coordinates: (2689, 12)
Initial DataFrame shape: (313, 12)
Shape after dropping NaN coordinates: (312, 12)
Initial DataFrame shape: (650, 12)
Shape after dropping NaN coordinates: (646, 12)
Warning: Missing columns ['alcaldia_hechos']. Skipping this DataFrame.
Initial DataFrame shape: (810, 12)
Shape after dropping NaN coordinates: (733, 12)
Initial DataFrame shape: (69, 12)
Shape after dropping NaN coordinates: (29, 12)
Initial DataFrame shape: (2951, 12)
Shape after dropping NaN coordinates: (1892, 12)
Initial DataFrame shape: (2452, 12)

C:\Users\eduar\AppData\Local\Temp\ipykernel_10412\3669253117.py:57: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')
C:\Users\eduar\AppData\Local\Temp\ipykernel_10412\3669253117.py:57: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')

Shape after dropping NaN coordinates: (2350, 12)
Initial DataFrame shape: (1147, 12)
Shape after dropping NaN coordinates: (1008, 12)
Initial DataFrame shape: (7274, 12)

C:\Users\eduar\AppData\Local\Temp\ipykernel_10412\3669253117.py:57: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')

Shape after dropping NaN coordinates: (6630, 12)
Initial DataFrame shape: (13447, 12)

C:\Users\eduar\AppData\Local\Temp\ipykernel_10412\3669253117.py:57: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['fecha_de_los_hechos'] = pd.to_datetime(df['fecha_de_los_hechos'], errors='coerce')

Shape after dropping NaN coordinates: (11908, 12)
Initial DataFrame shape: (23387, 12)
Shape after dropping NaN coordinates: (21246, 12)

In [42]:
all_geo = gpd.GeoDataFrame(pd.concat(gdf_list, ignore_index=True), crs="EPSG:6372")
all_geo = all_geo.to_crs("EPSG:6372")
all_geo

,id_ci,fecha_de_los_hechos,hora_de_los_hechos,alcaldia_hechos,colonia_hechos,calle_1_hechos,calle_2_hechos,tipo_impacto,delito,modalidad_delito,geometry
0,10019041,2025-01-01,12:00:00,cuauhtemoc,doctores,digna ochoa,vertiz,bajo impacto,delito de bajo impacto,falsedad ante autoridades,POINT (-99.148 19.425)
1,9940846,2025-01-04,17:25:00,iztapalapa,ejercito de oriente zona penon,rafael ballesteros,brigada carbajal,bajo impacto,delito de bajo impacto,narcomenudeo posesion simple,POINT (-99.026 19.369)
2,9960432,2025-01-05,00:25:00,cuauhtemoc,morelos,matamoros,sin registro,bajo impacto,delito de bajo impacto,narcomenudeo posesion simple,POINT (-99.131 19.447)
3,9987622,2025-01-06,12:00:00,xochimilco,cerrillos segunda seccion,jose beltran,no se especifica,bajo impacto,delito de bajo impacto,dano en propiedad ajena intencional a bienes i...,POINT (-99.018 19.246)
4,9996996,2025-01-06,22:00:00,cuauhtemoc,doctores,dr neva,sin registro,bajo impacto,delito de bajo impacto,lesiones intencionales por golpes,POINT (-99.145 19.409)
...,...,...,...,...,...,...,...,...,...,...,...
54232,10041466,NaT,21:00:00,iztacalco,ampliacion gabriel ramos millan,sur 157,oriente 120,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.098 19.386)
54233,10041471,NaT,20:30:00,gustavo a madero,arboledas de cuautepec el alto,tercera cerrada de joya de nieves,sin registro,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.126 19.558)
54234,10041472,NaT,10:30:00,miguel hidalgo,argentina poniente,general arista,sin registro,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.21 19.46)
54235,10041473,NaT,20:00:00,coyoacan,san francisco culhuacan,tercera cerrada de cinco de mayo via publica,sin registro,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.116 19.337)
54236,10041475,NaT,23:00:00,la magdalena contreras,el rosal,moctezuma,palmilla,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.251 19.308)

In [43]:
all_geo = all_geo.rename(columns={'geometry': 'geom'})

In [44]:
# Check for duplicates by all columns and drop them
if all_geo.duplicated().any():
    print(f"Found {all_geo.duplicated().sum()} duplicate rows. Dropping them.")
    all_geo = all_geo.drop_duplicates()

# Check for duplicates by 'id_ci' column and drop them
if 'id_ci' in all_geo.columns and all_geo.duplicated(subset=['id_ci']).any():
    print(f"Found {all_geo.duplicated(subset=['id_ci']).sum()} duplicate rows based on 'id_ci'. Dropping them.")
    all_geo = all_geo.drop_duplicates(subset=['id_ci'])

# Display the resulting DataFrame
# Reset the index of the DataFrame
all_geo = all_geo.reset_index(drop=True)
all_geo

Found 4222 duplicate rows. Dropping them.
Found 8049 duplicate rows based on 'id_ci'. Dropping them.

,id_ci,fecha_de_los_hechos,hora_de_los_hechos,alcaldia_hechos,colonia_hechos,calle_1_hechos,calle_2_hechos,tipo_impacto,delito,modalidad_delito,geom
0,10019041,2025-01-01,12:00:00,cuauhtemoc,doctores,digna ochoa,vertiz,bajo impacto,delito de bajo impacto,falsedad ante autoridades,POINT (-99.148 19.425)
1,9940846,2025-01-04,17:25:00,iztapalapa,ejercito de oriente zona penon,rafael ballesteros,brigada carbajal,bajo impacto,delito de bajo impacto,narcomenudeo posesion simple,POINT (-99.026 19.369)
2,9960432,2025-01-05,00:25:00,cuauhtemoc,morelos,matamoros,sin registro,bajo impacto,delito de bajo impacto,narcomenudeo posesion simple,POINT (-99.131 19.447)
3,9987622,2025-01-06,12:00:00,xochimilco,cerrillos segunda seccion,jose beltran,no se especifica,bajo impacto,delito de bajo impacto,dano en propiedad ajena intencional a bienes i...,POINT (-99.018 19.246)
4,9996996,2025-01-06,22:00:00,cuauhtemoc,doctores,dr neva,sin registro,bajo impacto,delito de bajo impacto,lesiones intencionales por golpes,POINT (-99.145 19.409)
...,...,...,...,...,...,...,...,...,...,...,...
41961,10041419,NaT,18:30:00,iztapalapa,lomas de la estancia,3a cerrada de estrella,no se especifica,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.004 19.331)
41962,10041429,NaT,03:40:00,iztapalapa,purisima atlazolpa,avenida canal de apatlaco,no se especifica,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.109 19.381)
41963,10041463,NaT,09:30:00,milpa alta,san miguel (santa ana tlacotenco),ricardo flores magon,carretera san gregorio oaxtepec,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.003 19.171)
41964,10041466,NaT,21:00:00,iztacalco,ampliacion gabriel ramos millan,sur 157,oriente 120,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.098 19.386)
41965,10041475,NaT,23:00:00,la magdalena contreras,el rosal,moctezuma,palmilla,bajo impacto,delito de bajo impacto,violencia familiar,POINT (-99.251 19.308)

## Split table

In [30]:
all_geo['delito'].value_counts()

delito
delito de bajo impacto                                     29894
robo a transeunte en via publica con y sin violencia        4217
robo de vehiculo con y sin violencia                        3607
robo a negocio con violencia                                1055
violacion                                                   1010
robo a pasajero a bordo del metro con y sin violencia        762
homicidio doloso                                             504
robo a repartidor con y sin violencia                        293
lesiones dolosas por disparo de arma de fuego                260
robo a casa habitacion con violencia                         131
robo a pasajero a bordo de microbus con y sin violencia      124
robo a cuentahabiente saliendo del cajero con violencia       50
robo a pasajero a bordo de taxi con violencia                 47
secuestro                                                      6
robo a transportista con y sin violencia                       6
Name: count, dtype: int64

In [45]:
# 1. Create the 'id' column from the DataFrame's index
all_geo['id'] = all_geo.index

# 2. Reorder the columns to place 'id' at the beginning (on the left)
cols = ['id'] + [col for col in all_geo.columns if col != 'id']
all_geo = all_geo[cols]

# 3. Create the points GeoDataFrame. 'id' is already the first column.
geo_points = all_geo[['id',  'delito', 'geom']]

# 4. Create the attributes DataFrame. 'id' will also be the first column here.
geo_attributes = all_geo.drop(columns=['geom', 'delito'])

In [46]:
geo_points

          id                  delito                    geom
0          0  delito de bajo impacto  POINT (-99.148 19.425)
1          1  delito de bajo impacto  POINT (-99.026 19.369)
2          2  delito de bajo impacto  POINT (-99.131 19.447)
3          3  delito de bajo impacto  POINT (-99.018 19.246)
4          4  delito de bajo impacto  POINT (-99.145 19.409)
...      ...                     ...                     ...
41961  41961  delito de bajo impacto  POINT (-99.004 19.331)
41962  41962  delito de bajo impacto  POINT (-99.109 19.381)
41963  41963  delito de bajo impacto  POINT (-99.003 19.171)
41964  41964  delito de bajo impacto  POINT (-99.098 19.386)
41965  41965  delito de bajo impacto  POINT (-99.251 19.308)

[41966 rows x 3 columns]

In [47]:
geo_attributes

,id,id_ci,fecha_de_los_hechos,hora_de_los_hechos,alcaldia_hechos,colonia_hechos,calle_1_hechos,calle_2_hechos,tipo_impacto,modalidad_delito
0,0,10019041,2025-01-01,12:00:00,cuauhtemoc,doctores,digna ochoa,vertiz,bajo impacto,falsedad ante autoridades
1,1,9940846,2025-01-04,17:25:00,iztapalapa,ejercito de oriente zona penon,rafael ballesteros,brigada carbajal,bajo impacto,narcomenudeo posesion simple
2,2,9960432,2025-01-05,00:25:00,cuauhtemoc,morelos,matamoros,sin registro,bajo impacto,narcomenudeo posesion simple
3,3,9987622,2025-01-06,12:00:00,xochimilco,cerrillos segunda seccion,jose beltran,no se especifica,bajo impacto,dano en propiedad ajena intencional a bienes i...
4,4,9996996,2025-01-06,22:00:00,cuauhtemoc,doctores,dr neva,sin registro,bajo impacto,lesiones intencionales por golpes
...,...,...,...,...,...,...,...,...,...,...
41961,41961,10041419,NaT,18:30:00,iztapalapa,lomas de la estancia,3a cerrada de estrella,no se especifica,bajo impacto,violencia familiar
41962,41962,10041429,NaT,03:40:00,iztapalapa,purisima atlazolpa,avenida canal de apatlaco,no se especifica,bajo impacto,violencia familiar
41963,41963,10041463,NaT,09:30:00,milpa alta,san miguel (santa ana tlacotenco),ricardo flores magon,carretera san gregorio oaxtepec,bajo impacto,violencia familiar
41964,41964,10041466,NaT,21:00:00,iztacalco,ampliacion gabriel ramos millan,sur 157,oriente 120,bajo impacto,violencia familiar
41965,41965,10041475,NaT,23:00:00,la magdalena contreras,el rosal,moctezuma,palmilla,bajo impacto,violencia familiar

## Save data

In [50]:
import os

# Define the output directory
output_dir = '../../../0_DATA/1_CLEAN/CRIMEN/'

# Create the directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# --- 1. Save the GeoDataFrame as a Shapefile (.shp) ---
# Note: Shapefiles truncate column names to 10 characters.
# 'tipo_impacto' will be saved as 'tipo_impa'.
points_filepath = os.path.join(output_dir, 'crime_points.parquet')
geo_points.to_parquet(points_filepath, index=False, engine='pyarrow')

# --- 2. Save the pandas DataFrame as a CSV file ---
# We use index=False because you already have a unique 'id' column.
attributes_filepath = os.path.join(output_dir, 'crime_attributes.parquet')
geo_attributes.to_parquet(attributes_filepath, index=False)